name: build
on:
  push:
    branches:
      - "master"
    tags:
      - "!*"
  pull_request:
    branches:
      - '*'
jobs:
  build:
    runs-on: ubuntu-latest
    name: build
    steps:
      - name: Set up Go 1.15
        uses: actions/setup-go@v1
        with:
          go-version: 1.15
      - name: Checkout
        uses: actions/checkout@v1
      - name: Get dependencies
        run: make deps
      - name: Build & Test
        run: make build
      - name: Validate release
        uses: goreleaser/goreleaser-action@v1
        with:
          args: release --snapshot --skip-publish --rm-dist
